### ISSUE TITLE
Private server support for arcai.js

### ISSUE THREAD

**Issue by koaps** [Arcath/screeps-code#3]
This is more of a feature, but I was playing with screeps-interface as an alternative to node-screeps-api so I can get private server support and I was able to get it to work for arcai.js.

This was the change I had to do:
```
program = require('commander')
const SODB = require('sodb')
const {table} = require('table')
const colors = require('colors')

var config = require('../private.json')

const api = new (require('screeps-interface'))(config)

//....

api.me()

api.memory()
  .then(memory => {
    var database = new SODB()

    memory.data.state.jobObjects.forEach(function(entry){
      if(entry != null){
        database.objects[entry.___id] = entry
      }
    })

//....
```

**Comment by Arcath** [comment]
is that with adding config to `private.json` for the server address?

I was looking at setting up my own private server for testing so will be looking at this shortly.

**Comment by koaps** [comment]
Ya, my private.json is like this:

```
{
  "username": "<USER>",
  "password": "<PASS>",
  "url": "<IP>",
  "port": 21025,
  "private": true,
  "branch": "default",
  "ptr": false
}
```
Think url and username as var names is in [screeps-interface](https://github.com/JestDotty/screeps-interface) so I tweaked by Gruntfile to use those, the [Advanced Grunt Usage](http://docs.screeps.com/contributed/advanced_grunt.html) page covers setting Grunt for private servers.

I used the [screepsmod-auth](https://github.com/ScreepsMods/screepsmod-auth) way on my private server for API auth
