### ISSUE TITLE
AI not creating upgraders

### ISSUE THREAD

**Issue by koaps** [Arcath/screeps-code#4]
I'm trying to figure out why when I leave the room for a while (not adding green flags to build stuff for example) no upgraders are ever created, at best builders are given upgrade jobs after they complete but they tend to do one upgrade job then stop and just tick down until it's time to recycle.

I left my room overnight and no upgraders were made so the controller was bad in shape when I checked it this morning.

I looked at the code and it seems like it should create upgraders, I tried changing the priority of the job to a 110 to bump it to the top so when I check later on I'll see if that helped.

The only thing I was playing with last night was changing the extensions for upgraders to be [WORK, CARRY] instead of just [WORK] to give them a bit more energy capacity.

**Comment by koaps** [comment]
Ok, I think I got it, looks like I have to have a container at my controller for the upgrader to get any work done.

Might be something to look at, like if there's no container for the upgrader to drop one and build it

**Comment by Arcath** [comment]
yeah builders/upgraders will only spawn and work from `generalUseContainers` which is any container not near a source or spawn.

You should only need to use green flags to build the spawn in new rooms, once a room has its spawn it should be able to build up by itself.

I use the room planner by dissi for my rooms now which usually means:

 - RCL1 build spawn + recycle container
 - RCL2 build extensions + upgraders container
 - RCL3 build tower + source containers + extensions

at this point the room will be ready to go.

**Comment by koaps** [comment]
Ah, ok that makes sense, what triggers the building of the recycle container?

I'm on RCL2 now (after resetting everything) and the creeps are just focused on upgrading, they haven't built anything yet, do I need to drop a flag?

I created a room planner file and see all the construction sites placed ok, before I would drop a green flag to kick off building but I wanted to see what happens if I let the AI just go on its own.
